<a href="https://colab.research.google.com/github/Bhairavi19/AI-ML-Implementation/blob/main/Model_Selection_for_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Random Forest Regression

## Importing the libraries

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Data Set Import

In [13]:
data_set = pd.read_csv('dataset.csv')
X = data_set.iloc[:, :-1].values
y = data_set.iloc[:, -1].values

## Splitting the dataset into the Training & Test set

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Random Forest Regression model Training on the Training set

In [15]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

## Test set results Predictions

In [16]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[434.05 431.23]
 [458.79 460.01]
 [463.02 461.14]
 ...
 [469.48 473.26]
 [439.57 438.  ]
 [460.38 463.28]]


## Model Performance Evaluation- Random Forest

In [17]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9615908334363876

# Polynomial Regression

## Importing the libraries

In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Data Set Import

In [19]:
data_set = pd.read_csv('dataset.csv')
X = data_set.iloc[:, :-1].values
y = data_set.iloc[:, -1].values

## Splitting the dataset into the Training & Test set

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Polynomial Regression model Training on the Training set

In [21]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression()

## Test set results Predictions

In [22]:
y_pred = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.66 463.28]]


## Model Performance Evaluation-- Polynomial regression

In [23]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9458192606428147

# Decision Tree Regression

## Importing the libraries

In [24]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Data Set Import

In [25]:
data_set = pd.read_csv('dataset.csv')
X = data_set.iloc[:, :-1].values
y = data_set.iloc[:, -1].values

## Splitting the dataset into the Training & Test set

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Decision Tree Regression model Training on the Training set

In [27]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 21)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=21)

## Test set results Predictions

In [28]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[431.28 431.23]
 [459.59 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.74 463.28]]


## Model Performance Evaluation- Decision Tree


In [29]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9185756259476033